### PR TITLE
Style changes (updated)

### PR DESCRIPTION
**Pull request by williamd1k0**
Same as pull request #3 but updated.

The changes don't include minified script, build with Grunt or ask me then I commit the script (`map.min.js`).
Thanks.

### CODE REVIEW

**Comment by mchristopher** [comment]
@williamd1k0 After looking at this in-browser, I think the lured pokestop icon needs something additional to indicate it's lured - for me the size difference isn't a large enough visual indicator. Would you mind adding something additional to the lure icon?

**Comment by williamd1k0** [comment]
Hmm, I see.
I'll try to improve the lure icon asap.
Thanks.

**Comment by williamd1k0** [comment]
@mchristopher , what do you think?

image

>Source
pstoplured

**Comment by mchristopher** [comment]
That looks great, thanks!

**Pull request merged**
